kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pagerduty-operator
  namespace: sre-pagerduty-operator
subjects:
- kind: ServiceAccount
  name: pagerduty-operator
roleRef:
  kind: Role
  name: pagerduty-operator
  apiGroup: rbac.authorization.k8s.io
