apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagerduty-operator
  namespace: pagerduty-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pagerduty-operator
  template:
    metadata:
      labels:
        name: pagerduty-operator
    spec:
      serviceAccountName: pagerduty-operator
      containers:
        - name: pagerduty-operator
          image: quay.io/app-sre/pagerduty-operator
          command:
          - pagerduty-operator
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "30m"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pagerduty-operator"
