apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagerduty-operator
  namespace: pagerduty-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pagerduty-operator
  template:
    metadata:
      labels:
        name: pagerduty-operator
    spec:
      serviceAccountName: pagerduty-operator
      containers:
        - name: pagerduty-operator
          #TODO Move to official quay namespace
          image: quay.io/whearn/pagerduty-operator:0.0.29
          command:
          - pagerduty-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pagerduty-operator"
